[tool.poetry]
name = "matrix-webhook"
version = "3.5.0"
description = "Post a message to a matrix room with a simple HTTP POST"
authors = ["Guilhem Saurel <guilhem.saurel@laas.fr>"]
license = "BSD-2-Clause"
readme = "README.md"
homepage = "https://github.com/nim65s/matrix-webhook"
repository = "https://github.com/nim65s/matrix-webhook.git"

[tool.poetry.urls]
"changelog" = "https://github.com/nim65s/matrix-webhook/blob/master/CHANGELOG.md"

[tool.poetry.dependencies]
python = "^3.8"
Markdown = "^3.3.4"
matrix-nio = ">=0.18.3,<0.21.0"

[tool.poetry.dev-dependencies]
httpx = "^0.23.0"
black = "^22.8.0"
coverage = "^6.4.4"
pydocstyle = "^6.1.1"
flake8 = "^5.0.4"
pyupgrade = "^2.31.0"

[tool.pydocstyle]
ignore = ["D200", "D203", "D204", "D212"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
matrix-webhook = "matrix_webhook.__main__:main"
